In [126]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine('postgresql://davidgrisales:password@localhost:5432/qversity')
def query(sql_query):
    return pd.read_sql_query(sql_query, engine)

In [191]:
# Extracting silver.customers as a dataframe
customers_df = query("SELECT * FROM silver.stg_customers")
print(customers_df.isnull().sum())

lat                       0
lon                       0
city                      0
email                     0
digital_engagement        0
credit_info               0
gender                   47
status                    0
address                  78
country                   0
last_name                 0
first_name                0
kyc_status                0
risk_score                0
customer_id               0
nationality               0
phone_number              0
date_of_birth             0
customer_segment          0
registration_date         0
relationship_manager    111
corrected_city_name       0
dtype: int64

We only have null values in gender, address and relationship manager, which should be reviewed.

# Customers

In [161]:
print(query("""
SELECT column_name, data_type, is_nullable
    FROM information_schema.columns
    WHERE table_schema = 'silver'
      AND table_name = 'stg_customers';
      """))

             column_name         data_type is_nullable
0                    lat  double precision         YES
1                    lon  double precision         YES
2                   city              text         YES
3                  email              text         YES
4     digital_engagement              text         YES
5            credit_info              text         YES
6                 gender              text         YES
7                 status              text         YES
8                address              text         YES
9                country              text         YES
10             last_name              text         YES
11            first_name              text         YES
12            kyc_status              text         YES
13            risk_score  double precision         YES
14           customer_id              text         YES
15           nationality              text         YES
16          phone_number              text         YES
17         date_of_birth              text         YES
18      customer_segment              text         YES
19     registration_date              text         YES
20  relationship_manager              text         YES
21   corrected_city_name              text         YES

## City

In [162]:
print(query("select distinct city from silver.stg_customers"))

                     city
0                 Mendoza
1             Fortaleza
2      Ciudad de Mexico
3                 Cordoba
4                Temuco
..                    ...
126                Salto
127                Rosaro
128                  Piua
129          Montevideo
130          Valparaiso

[131 rows x 1 columns]

As observed, some cities require basic corrections, such as removing leading and trailing whitespaces, while others need name corrections. To handle name corrections, we will use pg_trgm to identify similar city names. At the same time, we will retain only those city names that occur most frequently in the model, ensuring correctness based on the probability of occurrence.

## Email

In [167]:
print(query("select count(*) from silver.stg_customers where email not like '%%@%%'"))
print(query("select email from silver.stg_customers where email not like '%%@%%'"))

   count
0     50
                                email
0          federico.armengolgmail.com
1             elodia.marquesgmail.com
2              santino.perezgmail.com
3            lucía.pimentahotmail.com
4             noa.castillohotmail.com
5               duván.da pazgmail.com
6             alcira.ramirezyahoo.com
7            augusto.gonzalezlive.com
8           virginia.peraltayahoo.com
9   thiago emanuel.dominguezgmail.com
10         gabriel.de andahotmail.com
11             janeth.suarezyahoo.com
12       maria julia.pimentayahoo.com
13          timoteo.ávaloshotmail.com
14          yolima.gutierrezyahoo.com
15         juan manuel.silvagmail.com
16              nerea.rochaicloud.com
17       maría teresa.macedoyahoo.com
18                cecilia.callive.com
19               matteo.niñogmail.com
20          asunción.cardozoyahoo.com
21              theo.sánchezgmail.com
22        benjamin.rodríguezyahoo.com
23         alberto.freitashotmail.com
24             morena.vilahotmail.com
25        vitor hugo.avilésuol.com.br
26              jacobo.gomezyahoo.com
27            rafaél.maciasuol.com.br
28           leonel.rezendeicloud.com
29              diogo.lopezicloud.com
30               berta.feliuyahoo.com
31             linda.rochahotmail.com
32            xiomara.saizhotmail.com
33        vitor gabriel.carogmail.com
34        josé eduardo.lopezgmail.com
35          paulina.carbajalgmail.com
36       gabriel.vasconcelosyahoo.com
37     thiago gabriel.ruelasyahoo.com
38           lucca.calvillouol.com.br
39       juan cruz.sepúlvedagmail.com
40           agatha.vazquezbol.com.br
41             juan.gonzalezyahoo.com
42         alfredo.bermúdezbol.com.br
43            elías.valenciayahoo.com
44          rodrigo.sánchezbol.com.br
45               ana.cerveragmail.com
46              elena.amorósyahoo.com
47           tadeo.gutierrezyahoo.com
48              cruz.sánchezyahoo.com
49        nicolas.del valleuol.com.br

Several issues were identified here.
- We need to add the '@' after the customer's last_name.
- Remove leading and trailing spaces.
- Keep everything in lowercase.
In order to add the '@' we will add it after the last_name occurrence in the email, it is demostrated that it will work by the following code.

In [171]:
count1= query("select count(*) from silver.stg_customers where email not like '%%@%%'")['count'][0]
count2= query("select count(*) from silver.stg_customers where email not like '%%@%%' and email like concat('%%', lower(last_name), '%%')")['count'][0]
if (count1 == count2):
    print("All invalid emails contain the last name")
else:
    print("Not all invalid emails contain the last name")

All invalid emails contain the last name

## first_name and last_name

In [172]:
print(query("select first_name, last_name from silver.stg_customers limit 20"))

     first_name  last_name
0         María   Martinez
1   Encarnacion  Fernandez
2         David      Casas
3        Thiago       Ríos
4      Agostina    jIMÍNEZ
5      Martirio  Hernandez
6         JAIRO    HEREDIA
7        Carlos      Gomes
8         Henry    Cornejo
9         Marco  Rodriguez
10       Anabel   nOGUEIRA
11    Alejandra      Porto
12     Federico   armengol
13       Samuel     moreno
14        Vidal   Mendonça
15      Eutimio  Gutierrez
16       Elodia    marques
17         Raul     Codina
18     Valentin     Guzman
19      Lavínia      Ramos

First names and lastnames have inconsistent capitalization. We will normalize them to lowercase. If capitalization is needed later, it will be easier to apply using a lowercased column.

## Phone Number

In [173]:
print(query("select phone_number from silver.stg_customers limit 20"))

         phone_number
0       +512620450533
1       +526519017499
2       +513155383161
3       +553837402552
4          2915950716
5     +51  0815550786
6      +5982370266919
7       +558983437024
8   +598 878 983 3732
9       +551804399692
10      +518790231499
11      +567610650872
12      +523390296514
13      +526934794403
14      +577861064954
15      +548098769174
16      +578722358914
17     +5983091848824
18     +5981847071085
19      +565099290105

In [175]:
print(query("select (length(phone_number)- length(replace(phone_number, '+',''))) as occurrences from silver.stg_customers order by occurrences desc limit 10;"))

   occurrences
0            1
1            1
2            1
3            1
4            1
5            1
6            1
7            1
8            1
9            1

In [185]:
print(query("select phone_number, country from silver.stg_customers where phone_number not LIKE '+%%' order by country limit 20"))

        phone_number country
0   (+54) 3502232038      AR
1         4691263639      AR
2         5088595579      AR
3   (+54) 5544730137      AR
4         4902319720      AR
5         5720148094      AR
6   (+54) 3573272368      AR
7   (+54) 2981216144      AR
8         5602068042      AR
9   (+54) 5177584191      AR
10  (+54) 6772059380      AR
11        2455910245      AR
12        9649045500      AR
13  (+54) 1795169707      AR
14        1717811992      AR
15  (+54) 9273040759      AR
16  (+54) 1490003329      AR
17        2553173857      AR
18  (+54) 4684021524      AR
19  (+54) 4610910373      AR

We will normalize phone numbers with the standard E.164, in order to do that we need to keep only numbers and the symbol + at the beginning of the string. Also we need to add the country code for certain phone numbers that did not include it.

## Dates

In [188]:
print(query("select date_of_birth as format1 from silver.stg_customers where date_of_birth like '__-__-____' limit 10"))
print(query("select date_of_birth as format2 from silver.stg_customers where date_of_birth like '____-__-__' limit 10"))
print(query("select date_of_birth as format3 from silver.stg_customers where date_of_birth like '____/__/__' limit 10"))
print(query("select date_of_birth as format4 from silver.stg_customers where date_of_birth like '__/__/____' limit 10"))

      format1
0  10-16-1950
1  01-05-1952
2  06-15-1973
3  07-15-1953
4  07-08-1958
5  10-25-2005
6  07-07-1959
7  08-29-1982
8  10-31-2000
9  11-25-1997
      format2
0  1989-08-05
1  1965-03-07
2  1987-08-06
3  1979-01-27
4  1952-03-01
5  1956-05-09
6  1959-08-09
7  2003-08-16
8  1954-11-14
9  1993-11-09
Empty DataFrame
Columns: [format3]
Index: []
      format4
0  05/06/1956
1  05/04/1982
2  12/12/1994
3  13/10/1979
4  12/03/1979
5  06/07/1956
6  29/01/1985
7  31/08/1993
8  14/01/1976
9  17/07/1953

Based on the last output we can say that the three formats that we have are:
- MM-DD-YYYY
- YYYY-MM-DD
- DD/MM/YYYY

## Gender

In [192]:
print(query("select gender from silver.stg_customers limit 20"))

   gender
0   Other
1       F
2   Other
3       F
4       F
5   Other
6       F
7   Other
8       F
9       F
10      F
11      M
12      M
13    N/A
14      M
15      M
16  Other
17      F
18      M
19      F

In [195]:
print(query("select count(*) from silver.stg_customers where gender is null" ))

   count
0     47

In [197]:
print(query("select gender, count(*) from silver.stg_customers group by gender"))

  gender  count
0   None     47
1  Other   1510
2     NA     47
3            50
4   null     70
5    N/A     57
6      M   1573
7      F   1646

Based on the outputs we have three different values:
- M
- F
- Other

The other ones are null or missing values, we will keep the current conventions as they are.
The missing values will be considered null, and handling values such as "unknown" to the presentation layer.

## Nationality

In [200]:
print(query("select distinct nationality from silver.stg_customers limit 20"))
print(query("select count(*) from silver.stg_customers where nationality is null" ))

  nationality
0          BR
1          CL
2          MX
3          PE
4          CO
5          AR
6          UY
   count
0      0

The output demostrates that no missing values handling is required nor values correction for nationality, however, in order to keep convention, proper upper case will be kept and tested.

## Country

In [201]:
print(query("select distinct country from silver.stg_customers"))

  country
0      BR
1      CL
2      MX
3      PE
4      CO
5      AR
6      UY

No missing values is required here.
No different values handling is required here.

## Customer Segment

In [203]:
print(query("select distinct customer_segment from silver.stg_customers"))

   customer_segment
0              pyme
1               Sme
2            retail
3         minorista
4   Private_Banking
5               sme
6            RETAIL
7   PRIVATE_BANKING
8   private_banking
9              PYME
10           Retail
11          premium
12              SME
13          PREMIUM
14    banca_privada
15          Premium

In [205]:
print(query("select distinct lower(trim(customer_segment)) as customer_segment from silver.stg_customers"))

  customer_segment
0           retail
1        minorista
2              sme
3  private_banking
4          premium
5    banca_privada
6             pyme

The `customer_segment` field is expected to contain the following standardized values:

- `retail`
- `premium`
- `private_banking`
- `sme`

However, some records include Spanish variants that need to be translated and normalized as follows:

| Original Value | Standardized Value |
|----------------|---------------------|
| `banca_privada` | `private_banking`   |
| `minorista`     | `retail`            |
| `pyme`          | `sme`               |

> **Note:** `pyme` stands for *pequeña y mediana empresa* (small and medium enterprise).

Additionally, all values in the `customer_segment` field should be converted to lowercase to ensure consistency and support downstream processing and analysis.

## Status

In [207]:
print(query("select distinct lower(status) as status from silver.stg_customers"))

       status
0    inactive
1    inactivo
2      activo
3   suspended
4      active
5      closed
6  suspendido
7     cerrado

Similar to the `customer_segment` field, the `status` field contains values that are not consistently lowercase or are written in Spanish instead of English.

The expected standardized values are:

- `active`
- `inactive`
- `suspended`
- `closed`

The following Spanish variants must be translated and normalized:

| Original Value | Standardized Value |
|----------------|---------------------|
| `activo`       | `active`            |
| `inactivo`     | `inactive`          |
| `suspendido`   | `suspended`         |
| `cerrado`      | `closed`            |

Additionally, all values in the `status` field should be converted to **lowercase** to ensure consistency and support downstream processing and analysis.

## Know your customer status

In [210]:
print(query("select distinct kyc_status from silver.stg_customers"))

  kyc_status
0    expired
1   VERIFIED
2   REJECTED
3    PENDING
4    EXPIRED
5   verified
6   rejected
7    pending

In [209]:
print(query("select distinct lower(kyc_status) as kyc_status from silver.stg_customers"))

  kyc_status
0   verified
1   rejected
2    pending
3    expired

In this case we only need to lowercase the status to all of them match with the standard values:
- verified
- pending
- expired
- rejected
Aditionally, this field will be considered as not null.

## Address

In [221]:
print(query("select count(*) from silver.stg_customers where address is null" ))

   count
0     78

In [220]:
print(query("select length(address) as address_length from silver.stg_customers where address is not null order by address_length asc limit 20"))

    address_length
0                0
1                0
2                0
3                0
4                0
5                0
6                0
7                0
8                0
9                0
10               0
11               0
12               0
13               0
14               0
15               0
16               0
17               0
18               0
19               0

In [226]:
print(query("select count(*) from silver.stg_customers where length(address) < 20" ))

   count
0    315

In [224]:
print(query("select  address, count(*) from silver.stg_customers where length(address) < 10 and address is not null group by address limit 20"))

  address  count
0    null     78
1      NA     85
2     N/A     76
3             76

In [228]:
print(query("select address,length(address) as address_length from silver.stg_customers where length(address)>= 20 order by address_length asc limit 20"))

                               address  address_length
0         C. Toni Bou 704, Jaén, 03375              28
1      Via Iris Perelló 4, Jaén, 44449              31
2      Av. 1 N° 998, Salta 4400, Salta              31
3      Av. 6 N° 918, Salta 4400, Salta              31
4     Diag. 5 N° 82, Salta 4400, Salta              32
5     Plaza Laura Malo 71, Lugo, 14462              32
6    Via Gala Tomás 8, Palencia, 42647              33
7    Plaza Wálter Polo 66, León, 50047              33
8    Av. 4 N° 14, Merlo 5881, San Luis              33
9    Via Emma Serna 27, Sevilla, 31121              33
10   Pasaje Cleto Sosa 2, Cádiz, 16965              33
11   Via de Chus Cueto 4, Soria, 37574              33
12   C. Adela Nevado 47, Ciudad, 06159              33
13   Av. 1 N° 461, Rawson 9103, Chubut              33
14   Vial Timoteo Amo 71, Ceuta, 09590              33
15  Rambla Xavier Amat 76, Jaén, 43895              34
16  Cuesta de Paca Muro 3, León, 26478              34
17  Calle Sara Soto 74, Granada, 21115              34
18  C. Genoveva Badía 32, Ávila, 07402              34
19  Av. 3 N° 223, Merlo 5881, San Luis              34

In [230]:
print(query("select count(*) from silver.stg_customers where length(address) <> length(trim(regexp_replace(address, '\s+', ' ', 'g')))" ))

   count
0      2

The previous outputs show that null handling is necessary, as many missing values are not marked as None or null but rather as literals like 'null', 'n/a', or similar. Additionally, while most addresses already have correct spacing and no leading or trailing whitespace, enforcing these rules is appropriate to ensure all addresses conform to a consistent format.

## Risk Score

In [233]:
print(query("select min(risk_score), max(risk_score) from silver.stg_customers "))

    min    max
0  0.04  100.0

In [234]:
print(query("select count(*) risk_score from silver.stg_customers where risk_score is null" ))

   risk_score
0           0

Based on this, no further modifications are required for this column.

## Relationship Manager

In [235]:
print(query("select distinct relationship_manager from silver.stg_customers limit 20"))

   relationship_manager
0                  None
1      Sebastian Castro
2      Valentina Torres
3                    NA
4        Luis Hernandez
5         Diego Ramirez
6           Sofia Lopez
7         Daniela Rojas
8       Isabella Vargas
9          Lucia Ortega
10         Maria Garcia
11       Alejandro Diaz
12         Camila Reyes
13         Ana Martinez
14
15       Andres Morales
16                 null
17     Carlos Rodriguez
18      Nicolas Mendoza
19                  N/A

In [237]:
print(query("select  relationship_manager, count(*) from silver.stg_customers where length(relationship_manager) < 10 group by relationship_manager limit 20"))

  relationship_manager  count
0                   NA     76
1                          85
2                 null    124
3                  N/A    100

In [238]:
print(query("select count(*) from silver.stg_customers where relationship_manager is null" ))

   count
0    111

In [241]:
print(query("""select count(distinct relationship_manager) from silver.stg_customers where 
relationship_manager is not null and length(relationship_manager) > 10""" ))

   count
0     15

Based on the output, missing value handling is required to normalize null values by converting literal "null" strings into actual null values. Additionally, since there are 15 distinct null value representations, placing relationship_managers in a separate table seems logical.


## Latitude and Longitude
Standard values must be in the range of [-90,90] for the latitude and [-180,180] for the longitude.

In [146]:
print(query("select lon, lat, city,country from silver.stg_customers where abs(lon) > 180 or abs(lat) > 90"))

            lon         lat              city country
0    320.967539  121.853231         La Serena      CL
1   -259.444158   98.805649          Medellin      CO
2    151.775347  128.775969            Bogota      CO
3    214.494358    8.436911     Rio de Janero      BR
4    201.085476  112.030299           Tucuman      AR
..          ...         ...               ...     ...
335  343.168422   50.948891             Cusco      PE
336  166.068082 -115.731089         Fortaleza      BR
337  -61.073942  127.839725  Ciudad de Mexico      MX
338  -61.513193  197.045574           Mendoza      AR
339  385.620117  -64.161189          Trujillo      PE

[340 rows x 4 columns]

In [148]:
print(query("select lon, lat, city, country from silver.stg_customers where city = 'Medellin'"))

            lon        lat      city country
0   -259.444158  98.805649  Medellin      CO
1    -72.330731   8.577726  Medellin      CO
2    -72.903613   5.744502  Medellin      CO
3    -73.578732   6.281511  Medellin      CO
4    -77.744874   7.142953  Medellin      CO
..          ...        ...       ...     ...
110  -68.001191   1.880074  Medellin      CO
111  -69.132876   6.240431  Medellin      CO
112  -67.677496  10.361083  Medellin      CO
113  -72.050087   9.880225  Medellin      CO
114  -72.431450   5.126446  Medellin      CO

[115 rows x 4 columns]

In [152]:
print(query("select avg(lon), avg(lat), trim(lower(city)) as new_city from silver.stg_customers group by new_city order by new_city"))

          avg        avg      new_city
0  -79.066659  -7.982359      arequipa
1  -65.404333  -6.348039       arequpa
2  -71.440911   6.309575   barranquila
3  -64.445430   8.124095  barranquilla
4  -69.700905   8.654977        bogota
..        ...        ...           ...
64 -49.554959  -4.052993      trujillo
65 -56.575196 -10.754885       trujllo
66 -61.154148 -37.313165        tucman
67 -51.290403 -38.206856       tucuman
68 -66.239745 -32.234300    valparaiso

[69 rows x 3 columns]

In [150]:
print(query("select lon, lat, city,country from silver.stg_customers where city = 'Buenos Aires'"))

           lon        lat          city country
0   -54.151812 -40.872464  Buenos Aires      AR
1   -59.114962 -33.222440  Buenos Aires      AR
2   -69.413268 -54.063461  Buenos Aires      AR
3   -62.574659 -47.296418  Buenos Aires      AR
4   -68.405638 -54.030172  Buenos Aires      AR
..         ...        ...           ...     ...
116 -65.429024 -32.193757  Buenos Aires      AR
117 -65.499164 -50.938116  Buenos Aires      AR
118 -70.030464 -29.493226  Buenos Aires      AR
119 -60.359312 -29.500348  Buenos Aires      AR
120 -56.668474 -29.591404  Buenos Aires      AR

[121 rows x 4 columns]

In [153]:
print(query("select avg(lon), avg(lat) from silver.stg_customers where city = 'Medellin'"))

         avg        avg
0 -71.817943  12.143573

In [154]:
print(query("select percentile_cont(0.5) within group (order by lon) as median_lon, percentile_cont(0.5) within group (order by lat) as median_lat from silver.stg_customers where city = 'Medellin'"))

   median_lon  median_lat
0   -72.43145    7.359718

In [245]:
print(query("select count(*) from silver.stg_customers where abs(lon) > 180 or abs(lat) > 90" ))

   count
0    340

In [246]:
print(query("select city, country, lat, lon from silver.stg_customers where abs(lon) > 180 or abs(lat) > 90 limit 20"))

            city country         lat         lon
0      La Serena      CL  121.853231  320.967539
1       Medellin      CO   98.805649 -259.444158
2          Piura      PE -195.894404  148.205595
3      Fortaleza      BR   49.940711 -368.891950
4           Lima      PE -176.587205 -374.828537
5     Montevideo      UY  -67.449146  263.982072
6        Rosario      AR  159.707664  255.164625
7      La Serena      CL   29.017014 -274.129475
8       Maldonad      UY -113.686034   21.882952
9      Montevide      UY  199.820519  172.341332
10    Montevideo      UY  154.062557 -210.923761
11      Paysandu      UY  114.573335   81.501339
12        Cordba      AR -128.357506   96.217253
13     La Serena      CL  127.178001  115.526144
14       Tijuana      MX   68.253989 -212.609036
15      Brasilia      BR  -13.822239 -227.617715
16       Tucuman      AR  -90.932857  -46.087655
17     Monterrey      MX  196.450729 -122.566320
18      Maldonad      UY  126.439471  312.468137
19  Buenos Aires      AR  159.085905   41.733066

In [251]:
print(query("select lat, lon from silver.stg_customers where lower(city) = 'medellin' limit 20"))

          lat         lon
0    6.281511  -73.578732
1   98.805649 -259.444158
2    7.142953  -77.744874
3   10.997426  -69.764982
4    5.113929  -67.795807
5    6.366700  -72.151223
6    7.519364  -69.691521
7   11.509914  -67.546444
8    6.403397  -71.333666
9   11.912083  -69.574435
10   8.598686  -67.609846
11   2.756667  -68.280823
12   5.533147  -67.262941
13   3.695906  -71.503471
14   9.845996  -68.909587
15   8.067946  -70.025226
16  11.575456  -68.608678
17   9.926815  -71.266291
18  10.714167  -71.114906
19  10.500979  -77.280529

In [257]:
print(query("""
    SELECT 
        cust.city, 
        COUNT(*) AS bad_coord_count,
        total_counts.total_customer_count
    FROM silver.int_customers cust
    JOIN (
        SELECT city, COUNT(*) AS total_customer_count 
        FROM silver.int_customers 
        GROUP BY city
    ) AS total_counts ON cust.city = total_counts.city
    WHERE abs(cust.lon) > 180 OR abs(cust.lat) > 90 
    GROUP BY cust.city, total_counts.total_customer_count
    ORDER BY bad_coord_count DESC 
    limit 20;
"""))

                city  bad_coord_count  total_customer_count
0         Montevideo               18                   142
1          La Serena               16                   137
2            Tucuman               14                   126
3       Buenos Aires               13                   149
4           Paysandu               12                   137
5               Lima               12                   154
6            Cordoba               11                   144
7          Monterrey               11                   145
8          Maldonado               11                   142
9            Tijuana               11                   163
10         Fortaleza               11                   154
11         Cartagena               10                   143
12          Arequipa               10                   155
13            Rivera               10                   144
14  Ciudad De Mexico               10                   135
15            Temuco               10                   146
16          Salvador               10                   143
17             Cusco               10                   156
18          Trujillo                9                   124
19            Bogota                9                   127

In [261]:
 print(query(
    """
    SELECT 
    city,
    country,
     PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY lat) AS median_lat,
     PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY lon) AS median_lon,
    avg(lon) as avg_lon,
    avg(lat) as avg_lat
  FROM silver.int_customers
  WHERE lat BETWEEN -90 AND 90 
    AND lon BETWEEN -180 AND 180
  GROUP BY city, country
  """))

                city country  median_lat  median_lon     avg_lon    avg_lat
0           Arequipa      PE   -7.842783  -74.369206  -71.887768  -7.951093
1       Barranquilla      CO    6.294353  -71.597098  -72.111609   6.166103
2             Bogota      CO    6.366766  -71.781233  -69.741512   5.381097
3           Brasilia      BR  -15.434991  -56.475895  -55.210950 -14.615528
4       Buenos Aires      AR  -41.120001  -63.159899  -61.553084 -40.122935
5               Cali      CO    6.154130  -72.192907  -69.850083   6.209555
6          Cartagena      CO    6.434398  -72.298960  -72.981505   7.665563
7   Ciudad De Mexico      MX   23.349168 -102.286750 -100.276441  23.760783
8         Concepcion      CL  -36.879375  -70.328239  -68.718846 -35.982548
9            Cordoba      AR  -38.540253  -63.705062  -63.007584 -37.044721
10             Cusco      PE   -9.052912  -74.080214  -74.798678  -8.866672
11         Fortaleza      BR  -18.008461  -54.774411  -54.333000 -17.215814
12       Guadalajara      MX   23.133323 -100.901791  -99.366092  23.637681
13         La Serena      CL  -41.109195  -71.034503  -70.995142 -38.515470
14              Lima      PE   -8.354303  -73.843823  -72.884295  -7.493990
15         Maldonado      UY  -32.660376  -55.557965  -55.576843 -32.564272
16          Medellin      CO    6.774186  -72.623676  -72.972013   6.877068
17           Mendoza      AR  -38.811838  -64.266406  -62.773113 -38.066012
18         Monterrey      MX   24.610143 -100.528273 -101.675230  24.570318
19        Montevideo      UY  -32.714049  -55.329818  -55.759873 -32.992382
20          Paysandu      UY  -32.459678  -55.538223  -55.550712 -32.425077
21             Piura      PE   -9.237801  -74.464004  -72.565378  -8.684810
22            Puebla      MX   22.892882 -101.931644 -101.036724  23.988662
23    Rio De Janeiro      BR  -14.804582  -53.295846  -53.450977 -13.552109
24            Rivera      UY  -32.942830  -55.257985  -53.963973 -32.847940
25           Rosario      AR  -37.702517  -63.579322  -61.513674 -37.299942
26             Salto      UY  -32.833706  -55.579484  -54.478025 -32.286338
27          Salvador      BR  -15.154936  -52.750123  -52.239930 -15.712240
28          Santiago      CL  -38.760697  -70.934578  -71.392530 -38.074058
29         Sao Paulo      BR  -16.452566  -54.521585  -50.210998 -13.801500
30            Temuco      CL  -35.703226  -70.685984  -71.537231 -35.296176
31           Tijuana      MX   22.426448 -102.095265 -101.151208  22.311764
32          Trujillo      PE   -8.960451  -75.086730  -75.364882  -8.841191
33           Tucuman      AR  -38.740055  -61.603569  -62.001443 -38.911258
34        Valparaiso      CL  -36.247746  -70.767155  -70.693357 -34.061873

In [273]:
print(query("""
WITH geo_medians AS (
  SELECT 
    country, 
    city,
    PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY lat) AS median_lat,
    PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY lon) AS median_lon
  FROM silver.int_customers
  WHERE ABS(lat) <= 90 AND ABS(lon) <= 180
  GROUP BY country, city
)
SELECT 
  sc.country,
  sc.city,
  CASE 
    WHEN ABS(sc.lat) > 90 THEN gm.median_lat
    ELSE sc.lat
  END AS cleaned_lat,
  CASE 
    WHEN ABS(sc.lon) > 180 THEN gm.median_lon
    ELSE sc.lon
  END AS cleaned_lon
FROM silver.int_customers sc
LEFT JOIN geo_medians gm 
  ON sc.city = gm.city AND sc.country = gm.country;
"""))

     country        city  cleaned_lat  cleaned_lon
0         PE        Lima    -7.163663   -73.703814
1         MX   Monterrey    15.779936   -96.933420
2         PE    Trujillo    -7.427306   -75.446619
3         BR    Brasilia   -12.916234   -38.432789
4         CO    Medellin     6.281511   -73.578732
...      ...         ...          ...          ...
4995      BR   Fortaleza   -30.484525   -44.928434
4996      AR     Rosario   -41.022048   -53.232458
4997      BR    Salvador   -33.577485   -62.029926
4998      UY  Montevideo   -31.974402   -54.912704
4999      CL  Concepcion   -17.337974   -70.712960

[5000 rows x 4 columns]

In [270]:
print(query("select count(*) from silver.stg_customers where lat between 6.19 and 6.39 and lon between -75.7 and -75.54 and country='CO'"))
print(query("select count(*) from silver.stg_customers where country='CO'"))

   count
0      0
   count
0    704

In [271]:
print(query("select lat, lon, country, city from silver.stg_customers where city='Medellin'"))

           lat         lon country      city
0     6.281511  -73.578732      CO  Medellin
1    98.805649 -259.444158      CO  Medellin
2     7.142953  -77.744874      CO  Medellin
3    10.997426  -69.764982      CO  Medellin
4     5.113929  -67.795807      CO  Medellin
..         ...         ...     ...       ...
110   1.880074  -68.001191      CO  Medellin
111   9.880225  -72.050087      CO  Medellin
112   6.240431  -69.132876      CO  Medellin
113  10.361083  -67.677496      CO  Medellin
114   5.126446  -72.431450      CO  Medellin

[115 rows x 4 columns]

# Accounts EDA

In [80]:
import pandas as pd
accounts_df = pd.read_sql_table('stg_accounts', con=engine , schema='silver')
accounts_df.head()

,customer_id,account_id,status,balance,currency,branch_code,opened_date,account_type,credit_limit,interest_rate
0,CUST-0000001,ACC-7B841C599005,active,294632.84,USD,BR-320,2021-01-14,checking,NaN,20.33
1,CUST-0000001,ACC-385664AAA258,closed,171579.81,PEN,BR-487,2022-01-23,investment,NaN,2.87
2,CUST-0000001,ACC-94B1E2D62CFF,closed,414702.33,USD,BR-181,03-01-2024,savings,NaN,15.65
3,CUST-0000001,ACC-DAA30BD045F9,cerrado,703233.52,PEN,BR-763,2021-12-15,checking,NaN,11.61
4,CUST-0000001,ACC-DE7103A41227,closed,988158.77,PEN,BR-801,2023-03-01,savings,NaN,6.50

In [82]:
accounts_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17529 entries, 0 to 17528
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    17529 non-null  object
 1   account_id     17529 non-null  object
 2   status         17529 non-null  object
 3   balance        17043 non-null  float64
 4   currency       17529 non-null  object
 5   branch_code    17529 non-null  object
 6   opened_date    17529 non-null  object
 7   account_type   17529 non-null  object
 8   credit_limit   4461 non-null   float64
 9   interest_rate  17529 non-null  float64
dtypes: float64(3), object(7)
memory usage: 1.3+ MB

In [83]:
null_counts = accounts_df.isnull().sum()
print(null_counts)

customer_id          0
account_id           0
status               0
balance            486
currency             0
branch_code          0
opened_date          0
account_type         0
credit_limit     13068
interest_rate        0
dtype: int64

## Account ID

In [275]:
print(query("select count(distinct account_id) from silver.stg_accounts"))
if query("select count(distinct account_id) from silver.stg_accounts")['count'][0] == query("select count(*) from silver.stg_accounts")['count'][0]:
    print("No duplicate account_id values")
else:    print("There are duplicate account_id values")

   count
0  17529
No duplicate account_id values

## Account Type

In [281]:
print(query("select distinct account_type from silver.stg_accounts"))

       account_type
0          savings
1     credit_card
2       credit_card
3     credit_card
4        checking
5          checking
6           savings
7        checking
8       investment
9      investment
10         checking
11        savings
12     investment
13        savings
14       investment
15     credit_card
16          savings
17       investment
18      credit_card
19        checking

In [284]:
print(query("select count(*) from silver.stg_accounts where account_type is null" ))

   count
0      0

In [282]:
print(query("select distinct trim(lower(account_type)) from silver.stg_accounts;"))

         btrim
0     checking
1      savings
2   investment
3  credit_card

In [280]:
print(query("select distinct trim(lower(account_type)) from silver.stg_accounts where length(trim(lower(account_type))) < 4;"))

Empty DataFrame
Columns: [btrim]
Index: []

The required normalization for the `account_type` field consists of:

1. **Trim whitespace** – Remove any leading or trailing spaces
2. **Convert to lowercase** – Ensure all values are uniformly lowercase

However, exploratory data analysis (EDA) confirms that this transformation is **not necessary**, as all values are already in lowercase.

## Currency

In [285]:
print(query("SELECT distinct currency FROM silver.stg_accounts LIMIT 10;"))

  currency
0      COP
1      ARS
2      UYU
3      MXN
4      PEN
5      BRL
6      CLP
7      USD

No changes are required for the `currency` field. All values are already aligned with the expected constraints. Uppercase formatting is standard and acceptable for this field.

## Balance

In [113]:
query("select min(balance), max(balance) from silver.stg_accounts;")

      min           max
0  237.85  1.999231e+09

In [119]:
query("select * from silver.stg_accounts where balance is null limit 10;")

,customer_id,account_id,status,balance,currency,branch_code,opened_date,account_type,credit_limit,interest_rate
0,CUST-0000018,ACC-6EA2141F2ACE,closed,None,MXN,BR-843,03-19-2022,checking,NaN,8.15
1,CUST-0000021,ACC-39B99DD4C68D,FROZEN,None,COP,BR-884,2026-03-25,credit_card,71491473.07,23.63
2,CUST-0000037,ACC-EFD4AF498112,active,None,USD,BR-868,2021-04-20,savings,NaN,7.84
3,CUST-0000039,ACC-E2C4DB72051C,active,None,UYU,BR-321,2026-01-27,checking,NaN,7.29
4,CUST-0000058,ACC-49980AE4FC6B,active,None,USD,BR-346,2026-04-13,credit_card,46523.37,21.02
5,CUST-0000068,ACC-2ADA981BAF35,active,None,USD,BR-985,2025-03-21,credit_card,4393.21,12.24
6,CUST-0000069,ACC-3D8D7D7AE02A,frozen,None,USD,BR-566,2024-05-14,investment,NaN,11.95
7,CUST-0000070,ACC-697BFD0B7869,frozen,None,USD,BR-174,08-02-2021,checking,NaN,10.61
8,CUST-0000077,ACC-8AD2C23AC33C,closed,None,USD,BR-865,2025-06-19,checking,NaN,9.43
9,CUST-0000087,ACC-B4763072C3FD,Closed,None,USD,BR-230,2024-08-01,savings,NaN,17.68

In [293]:
print(query("select balance, account_id, currency, account_type from silver.stg_accounts where balance is not null and balance >0 order by balance asc"))

            balance        account_id currency account_type
0      2.378500e+02  ACC-BA96A3696EE5      USD   investment
1      2.656000e+02  ACC-3DB8545C6C5D      USD  credit_card
2      3.006300e+02  ACC-5F45C7E1C2D9      USD     checking
3      3.024300e+02  ACC-9A722F6B842C      USD  credit_card
4      3.078800e+02  ACC-DCE977E1856C      USD  credit_card
...             ...               ...      ...          ...
17038  1.990499e+09  ACC-38813697AE78      COP   investment
17039  1.992193e+09  ACC-617A22CE28B9      COP      savings
17040  1.994441e+09  ACC-D3B043CABFDE      COP  credit_card
17041  1.995661e+09  ACC-60B81E0D1E8E      COP  credit_card
17042  1.999231e+09  ACC-2268D732C07A      COP   investment

[17043 rows x 4 columns]

In [294]:
print(query("select distinct account_id, currency, account_type from silver.stg_accounts where balance is null limit 20"))

          account_id currency    account_type
0   ACC-D1E3719F0EDD      ARS        checking
1   ACC-4F04B4FD23CD      COP      investment
2   ACC-74FF2D8E6ADD      CLP        checking
3   ACC-1967085F4D00      ARS      investment
4   ACC-8A36C8629CF8      BRL        checking
5   ACC-534C67CAA7AE      BRL         savings
6   ACC-E474E8C4540A      UYU        checking
7   ACC-14213A0A43F9      ARS      investment
8   ACC-302771B5732E      ARS        checking
9   ACC-8714C74CB0B4      ARS     credit_card
10  ACC-B64BE7521FBE      USD     credit_card
11  ACC-D02C80DCB539      USD        checking
12  ACC-82B52CED8EE4      MXN     credit_card
13  ACC-11ED21DF434A      USD         savings
14  ACC-426DB1A35A95      USD         savings
15  ACC-475C6F4AB891      USD        checking
16  ACC-586C653061F0      USD    investment
17  ACC-EBB15CB3E92B      USD         savings
18  ACC-CB6A80F6393E      MXN        checking
19  ACC-F806DBE82221      USD        checking

In [296]:
print(query("select type, amount, status, account_id from silver.stg_transactions where account_id = 'ACC-D1E3719F0EDD'"))

       type amount  status        account_id
0  deposito   None  failed  ACC-D1E3719F0EDD

In [306]:
print(query("select type, amount, status, account_id from silver.stg_transactions where account_id in (select account_id from silver.stg_accounts where balance is null) and status='completed' limit 20"))

          type       amount     status        account_id
0     transfer     53968.09  completed  ACC-6EA2141F2ACE
1      deposit          NaN  completed  ACC-6EA2141F2ACE
2       refund    703825.22  completed  ACC-6EA2141F2ACE
3      payment    111089.81  completed  ACC-6EA2141F2ACE
4       retiro     44724.27  completed  ACC-ECCB48D515D4
5      payment       110.53  completed  ACC-FB4A5F405C22
6      deposit     47834.44  completed  ACC-49980AE4FC6B
7      deposit     13039.46  completed  ACC-3D8D7D7AE02A
8   Withdrawal    136891.42  completed  ACC-91ADF07A88F3
9          fee     18624.52  completed  ACC-697BFD0B7869
10         fee      4624.33  completed  ACC-69C9BB53BE94
11    transfer    178282.78  completed  ACC-69C9BB53BE94
12    transfer    129066.46  completed  ACC-E2C4DB72051C
13  withdrawal    996914.51  completed  ACC-E2C4DB72051C
14  Withdrawal     39922.56  completed  ACC-2ADA981BAF35
15    comision    389396.61  completed  ACC-60C6BE971102
16         fee     44499.33  completed  ACC-499383976E2C
17    transfer    244599.20  completed  ACC-499383976E2C
18    transfer  46053163.78  completed  ACC-60C6BE971102
19     payment   3501576.12  completed  ACC-60C6BE971102

In [305]:
print(query("select type, amount, status, account_id from silver.stg_transactions where account_id in (select account_id from silver.stg_accounts where balance is null) order by account_id limit 20"))

          type       amount     status        account_id
0   withdrawal     36900.68    pending  ACC-004B39592CF4
1       retiro     45855.34    pending  ACC-004B39592CF4
2         Pago     39386.87    pending  ACC-004B39592CF4
3      deposit  64824951.62     failed  ACC-004B39592CF4
4      deposit   1257859.13     failed  ACC-005567197180
5     transfer          NaN    pending  ACC-005567197180
6     transfer    725277.51     failed  ACC-005567197180
7     transfer      2457.07  completed  ACC-005D223E64B4
8   withdrawal          NaN     failed  ACC-005D223E64B4
9      deposit     23346.75   reversed  ACC-005D223E64B4
10         fee     21141.44    pending  ACC-005D223E64B4
11     payment          NaN     failed  ACC-005D223E64B4
12  withdrawal     41319.05     failed  ACC-005D223E64B4
13         fee     49530.35    PENDING  ACC-005D223E64B4
14     payment     45081.04     failed  ACC-01EE038AB006
15    transfer      1202.68    pending  ACC-01EE038AB006
16         fee     23462.19    pending  ACC-01EE038AB006
17     payment      3035.82  completed  ACC-03C39E07E287
18         fee     45829.88     failed  ACC-03C39E07E287
19     deposit    377577.31  completed  ACC-0410EDEFC0FD

In [304]:
print(query("select balance, account_id, currency from silver.stg_accounts where account_id='ACC-000048B22364'"))

     balance        account_id currency
0  358874.73  ACC-000048B22364      USD

In [120]:
query("select * from silver.stg_accounts where balance is not null limit 10;")

,customer_id,account_id,status,balance,currency,branch_code,opened_date,account_type,credit_limit,interest_rate
0,CUST-0000001,ACC-7B841C599005,active,2.946328e+05,USD,BR-320,2021-01-14,checking,NaN,20.33
1,CUST-0000001,ACC-385664AAA258,closed,1.715798e+05,PEN,BR-487,2022-01-23,investment,NaN,2.87
2,CUST-0000001,ACC-94B1E2D62CFF,closed,4.147023e+05,USD,BR-181,03-01-2024,savings,NaN,15.65
3,CUST-0000001,ACC-DAA30BD045F9,cerrado,7.032335e+05,PEN,BR-763,2021-12-15,checking,NaN,11.61
4,CUST-0000001,ACC-DE7103A41227,closed,9.881588e+05,PEN,BR-801,2023-03-01,savings,NaN,6.50
5,CUST-0000002,ACC-3F3F63EE6C0B,closed,1.728436e+05,USD,BR-360,2025-09-11,savings,NaN,19.77
6,CUST-0000002,ACC-A7D4F2BC48B7,frozen,8.456400e+02,USD,BR-171,20240205,savings,NaN,23.18
7,CUST-0000003,ACC-E8A50B6E5699,closed,4.726178e+05,USD,BR-303,2025-01-04,savings,NaN,24.70
8,CUST-0000003,ACC-B879137EBCAE,closed,5.332663e+04,USD,BR-381,2025-01-21,credit_card,38755.07,9.29
9,CUST-0000003,ACC-F6795B501588,closed,4.325431e+08,CLP,BR-735,01/10/2025,savings,NaN,18.76

## Credit Limit

In [308]:
print(query("select count(*) from silver.stg_accounts where lower(trim(account_type)) = 'credit_card' and credit_limit is null"))

   count
0      0

In [310]:
print(query("select credit_limit from silver.stg_accounts where credit_limit is not null limit 20"))

    credit_limit
0   3.875507e+04
1   4.109820e+04
2   2.371930e+08
3   3.993098e+07
4   8.487006e+04
5   1.189323e+06
6   1.555218e+06
7   2.602109e+04
8   4.386948e+04
9   4.051100e+03
10  3.929753e+05
11  3.313450e+05
12  9.378020e+07
13  8.568508e+05
14  2.291485e+04
15  3.107782e+06
16  6.402150e+06
17  8.887040e+04
18  2.157637e+05
19  7.544437e+04

In [313]:
print(query("""
SELECT
    CAST(credit_limit AS DECIMAL(18, 2)) AS credit_limit
FROM silver.stg_accounts where credit_limit is not null"""))

      credit_limit
0     3.875507e+04
1     4.109820e+04
2     2.371930e+08
3     3.993098e+07
4     8.487006e+04
...            ...
4456  1.962715e+07
4457  4.302238e+04
4458  4.744122e+07
4459  2.350364e+07
4460  7.759629e+07

[4461 rows x 1 columns]

In [311]:
print(query("select count(*) from silver.stg_accounts where lower(trim(account_type)) != 'credit_card' and credit_limit is not null"))

   count
0      0

Based on the outputs, no account with credit_card type has a null credit_limit. And viceversa, no account that's not a credit_card type has a credit_limit.
However, normalizing the data from scientific format to decimal format is suitable.

In [124]:
query("select type, currency, sum(amount) as total_amount from silver.stg_transactions where account_id='ACC-6EA2141F2ACE' group by type, currency")

       type currency  total_amount
0   deposit      MXN           NaN
1       fee      MXN     843786.61
2       FEE      MXN     426029.49
3   payment      MXN     459612.45
4    refund      MXN    1488640.84
5  transfer      MXN     461114.93

## Interest Rate

In [319]:
print(query("select count(*) as count_null_interest_rates from silver.stg_accounts where interest_rate is null"))
print(query("select count(*) as count_non_null_interest_rates from silver.stg_accounts where interest_rate is not null"))

   count_null_interest_rates
0                          0
   count_non_null_interest_rates
0                          17529

In [316]:
print(query("select interest_rate from silver.stg_accounts where interest_rate is not null limit 20"))

    interest_rate
0           20.33
1            2.87
2           15.65
3           11.61
4            6.50
5           19.77
6           23.18
7           24.70
8            9.29
9           18.76
10          21.61
11          24.17
12          13.34
13           9.06
14          16.56
15           3.50
16          18.17
17          11.70
18          11.06
19          22.79

In [318]:
print(query("select min(interest_rate) as min_interest_rate, max(interest_rate) as max_interest_rate from silver.stg_accounts where interest_rate is not null"))

   min_interest_rate  max_interest_rate
0                0.5               25.0

Based on the outputs, this column requires no cleaning.

## Opened Date

In [320]:
print(query("select count(*) from silver.stg_accounts where opened_date is null"))

   count
0      0

In [321]:
print(query("""select length(opened_date) as opened_date_length, count(*) as count from silver.stg_accounts
group by length(opened_date) order by opened_date_length asc limit 20
"""))

   opened_date_length  count
0                   8   1082
1                  10  16447

In [322]:
print(query("select count(*) from silver.stg_accounts where opened_date like '____-__-__'"))
print(query("select count(*) from silver.stg_accounts where opened_date like '__/__/____'"))
print(query("select count(*) from silver.stg_accounts where opened_date like '__-__-____'"))

   count
0  14337
   count
0   1067
   count
0   1043

In [325]:
print(query("select opened_date from silver.stg_accounts where opened_date like '____-__-__' limit 10"))
print(query("select opened_date from silver.stg_accounts where opened_date like '__/__/____' limit 10"))
print(query("select opened_date from silver.stg_accounts where opened_date like '__-__-____' limit 10"))

  opened_date
0  2021-01-14
1  2022-01-23
2  2021-12-15
3  2023-03-01
4  2025-09-11
5  2025-01-04
6  2025-01-21
7  2023-03-06
8  2023-02-08
9  2024-11-16
  opened_date
0  01/10/2025
1  28/12/2024
2  04/08/2025
3  06/02/2025
4  05/03/2026
5  03/06/2025
6  19/08/2023
7  28/07/2025
8  26/02/2023
9  23/11/2022
  opened_date
0  03-01-2024
1  03-01-2024
2  08-27-2025
3  04-10-2026
4  04-09-2026
5  06-03-2022
6  03-19-2022
7  07-07-2023
8  11-14-2025
9  12-31-2025

In [324]:
print(query("select opened_date from silver.stg_accounts where length(opened_date) < 10 limit 10"))

  opened_date
0    20240205
1    20240921
2    20241219
3    20251031
4    20251203
5    20260217
6    20250630
7    20230112
8    20220517
9    20250520

In this case it has been demostrated that we have four different formats for the dates:
- YYYY-MM-DD
- DD/MM/YYYY
- MM-DD-YYYY
- YYYYMMDD

Additionally, we have to null opened_dates, which is ideal to track bank activity.

## status

In [328]:
print(query("select count(*) from silver.stg_accounts where status is null"))

   count
0      0

In [329]:
print(query("select distinct status from silver.stg_accounts"))

       status
0      ACTIVE
1      active
2      closed
3   congelado
4      Closed
5      Frozen
6      CLOSED
7      FROZEN
8      Active
9      activo
10    cerrado
11     frozen

In [330]:
print(query("select distinct lower(trim(status)) as status from silver.stg_accounts"))

      status
0     active
1     closed
2  congelado
3     activo
4    cerrado
5     frozen

The `account_status` field has three possible standardized values:

- `active`
- `closed`
- `frozen`

All values must be converted to **lowercase**. Additionally, the following Spanish variants must be translated and normalized:

| Original Value | Standardized Value |
|----------------|---------------------|
| `activo`       | `active`            |
| `cerrado`      | `closed`            |
| `congelado`    | `frozen`            |

No null values were encountered.

## Branch Code

In [331]:
print(query("select branch_code from silver.stg_accounts limit 20"))

   branch_code
0       BR-320
1       BR-487
2       BR-181
3       BR-763
4       BR-801
5       BR-360
6       BR-171
7       BR-303
8       BR-381
9       BR-735
10      BR-539
11      BR-190
12      BR-178
13      BR-302
14      BR-693
15      BR-354
16      BR-415
17      BR-963
18      BR-683
19      BR-358

In [332]:
print(query("select count(*) from silver.stg_accounts where branch_code is null" ))

   count
0      0

In [333]:
print(query("select count(distinct branch_code) from silver.stg_accounts"))

   count
0    900

In [334]:
print(query("select count(distinct lower(trim(branch_code))) from silver.stg_accounts"))

   count
0    900

Branch Code does not require cleaning, however removing trailing and leading spaces must be enforced.

# Transactions EDA

In [336]:
import pandas as pd
transactions_df = pd.read_sql_table('stg_transactions', con=engine , schema='silver')
transactions_df.head()

,customer_id,transaction_id,date,type,amount,status,channel,category,currency,merchant,account_id,description
0,CUST-0000002,TXN-01BCC68DAF12,2025-08-07,deposit,33169.71,failed,branch,entertainment,USD,Starbucks,ACC-A7D4F2BC48B7,Esto etapa civil pronto programas cuestión tener.
1,CUST-0000002,TXN-5C9DC0068BEF,2026-02-14,refund,15048.19,failed,branch,entertainment,USD,PedidosYa,ACC-3F3F63EE6C0B,Papel oposición han resulta autor así.
2,CUST-0000002,TXN-C4746D437753,2026-03-20,refund,33193.03,failed,web,N/A,USD,Carrefour,ACC-3F3F63EE6C0B,Deleniti modi consequuntur delectus iure.
3,CUST-0000002,TXN-FEC92C6270B1,20251225,payment,19199.54,reversed,mobile,insurance,USD,Carrefour,ACC-3F3F63EE6C0B,Mi premio encontrar septiembre.
4,CUST-0000002,TXN-052E7623204F,2024-06-20,refund,44571.40,reversed,pos,other,USD,Amazon,ACC-A7D4F2BC48B7,Distinctio id animi fugiat voluptates eaque quos.

In [337]:
transactions_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87686 entries, 0 to 87685
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     87686 non-null  object
 1   transaction_id  87686 non-null  object
 2   date            87686 non-null  object
 3   type            87686 non-null  object
 4   amount          85067 non-null  float64
 5   status          87686 non-null  object
 6   channel         87686 non-null  object
 7   category        86861 non-null  object
 8   currency        87686 non-null  object
 9   merchant        86189 non-null  object
 10  account_id      87686 non-null  object
 11  description     85826 non-null  object
dtypes: float64(1), object(11)
memory usage: 8.0+ MB

In [338]:
transactions_df.isnull().sum()

customer_id          0
transaction_id       0
date                 0
type                 0
amount            2619
status               0
channel              0
category           825
currency             0
merchant          1497
account_id           0
description       1860
dtype: int64

## Customer_id

In [339]:
print(query("select count(*) from silver.stg_transactions where customer_id is null" ))

   count
0      0

In [340]:
print(query("""select count(*) from silver.stg_transactions where customer_id not in
(select customer_id from silver.stg_customers)"""))

   count
0      0

## Account_id

In [342]:
print(query("select count(*) from silver.stg_accounts where account_id is null" ))

   count
0      0

In [341]:
print(query("""
select count(*) from silver.stg_transactions where account_id not in
(select account_id from silver.stg_accounts)
"""))

   count
0      0

## Date

In [343]:
print(query("select count(*) from silver.stg_transactions where date is null" ))

   count
0      0

In [345]:
print(query("""select length(date) as date_length, count(*) from silver.stg_transactions
group by length(date) 
 """))

   date_length  count
0           10  82250
1            8   5436

In [352]:
format_1_count=query("select count(*) from silver.stg_transactions where date like '____-__-__'")
format_2_count=query("select count(*) from silver.stg_transactions where date like '__-__-____'")
format_3_count=query("select count(*) from silver.stg_transactions where date like '__/__/____'")
format_4_count=query("select count(*) from silver.stg_transactions where date like '________'")
total_count=query("select count(*) from silver.stg_transactions")
if (format_1_count['count'][0] + format_2_count['count'][0] + format_3_count['count'][0] \
    + format_4_count['count'][0]) == total_count['count'][0]:
    print("All date values fit into one of the four formats")
-

All date values fit into one of the four formats

In [353]:
print(query("select date from silver.stg_transactions where date like '________' limit 10"))
print(query("select date from silver.stg_transactions where date like '__-__-____' limit 10"))
print(query("select date from silver.stg_transactions where date like '____-__-__' limit 10"))
print(query("select date from silver.stg_transactions where date like '____-__-__' limit 10"))

       date
0  20251225
1  20240926
2  20250420
3  20240510
4  20251227
5  20260113
6  20250918
7  20260303
8  20251203
9  20260419
         date
0  01-02-2026
1  04-09-2026
2  03-15-2026
3  04-04-2025
4  04-18-2026
5  04-02-2026
6  04-07-2026
7  01-07-2026
8  12-08-2025
9  04-26-2026
         date
0  2025-08-07
1  2026-02-14
2  2026-03-20
3  2024-06-20
4  2026-02-18
5  2026-01-23
6  2025-12-28
7  2026-03-28
8  2024-05-09
9  2025-04-10
         date
0  2025-08-07
1  2026-02-14
2  2026-03-20
3  2024-06-20
4  2026-02-18
5  2026-01-23
6  2025-12-28
7  2026-03-28
8  2024-05-09
9  2025-04-10

In this case it has been demostrated that we have four different formats for the dates:
- YYYY-MM-DD
- DD/MM/YYYY
- MM-DD-YYYY
- YYYYMMDD

Additionally, we have to null dates.

In [355]:
print(query("select * from silver.stg_transactions where amount is null limit 10"))

    customer_id    transaction_id        date        type amount     status  \
0  CUST-0000013  TXN-EE9C128AC60B  2024-03-18      REFUND   None     failed
1  CUST-0000013  TXN-60DF552BF0D6  2025-04-15  withdrawal   None    pending
2  CUST-0000014  TXN-13FB6856F6D8  2024-04-25     deposit   None    pending
3  CUST-0000012  TXN-F685CD4683A8  2025-12-26  withdrawal   None     failed
4  CUST-0000012  TXN-5A92B9387447  2026-04-21    transfer   None    pending
5  CUST-0000059  TXN-D0F067E1141B  2024-09-26    TRANSFER   None     failed
6  CUST-0000017  TXN-BDADC5A7815E  2026-03-07  withdrawal   None     failed
7  CUST-0000017  TXN-EA2E5D10F44A  2025-05-09         fee   None   reversed
8  CUST-0000034  TXN-9619098F252D  2025-10-14     deposit   None    pending
9  CUST-0000034  TXN-F19266C29DF2  2024-09-23         fee   None  completed

  channel      category currency    merchant        account_id  \
0     web     education      USD    Movistar  ACC-0194AA1A6186
1  branch  subscription      USD              ACC-0194AA1A6186
2  branch      shopping      MXN   Liverpool  ACC-B756CAFF3B82
3  branch     transport      BRL     Spotify  ACC-22514F2FB6FF
4  mobile        travel      BRL        Oxxo  ACC-22514F2FB6FF
5     web        dining      UYU  HomeCenter  ACC-EC305826A550
6     pos           N/A      ARS      Coppel  ACC-20EEEAD91738
7     atm        dining      USD     Spotify  ACC-93F6260D16F0
8     web     utilities      COP  HomeCenter  ACC-B7DB56E20A94
9     web        salary      USD      Amazon  ACC-15FF740B0E92

                                         description
0                               Esto he consejo voy.
1                 Miguel embargo música lugar casos.
2          Pequeño poner valor administración siglo.
3            Proceso habría padre causa tipos orden.
4                            San quizá través igual.
5                  Dolorem nesciunt neque iure modi.
6  Tú tiempos resultados éste pueblo voz pueblo s...
7                       Ea in harum alias provident.
8                                                 NA
9         Punto exterior minutos lado medios nuevas.

In [356]:
print(query("""
SELECT 
    trim(lower(type)) as type,
    trim(lower(status)) as status,
    COUNT(*) as total,
    COUNT(*) FILTER (WHERE amount IS NULL) as null_amounts,
    ROUND(100.0 * COUNT(*) FILTER (WHERE amount IS NULL) / COUNT(*), 2) as null_percentage
FROM silver.stg_transactions
GROUP BY trim(lower(type)), trim(lower(status))
ORDER BY null_percentage DESC;
"""))

             type     status  total  null_amounts  null_percentage
0       reembolso     failed    182            11             6.04
1       reembolso  completed    168             8             4.76
2        comision     failed    295            14             4.75
3   transferencia    pending    175             8             4.57
4   transferencia   reversed    180             8             4.44
5       reembolso    pending    209             9             4.31
6        deposito    pending    306            13             4.25
7        comision  completed    299            12             4.01
8          retiro     failed    299            12             4.01
9        transfer    pending   3432           118             3.44
10           pago  completed    322            11             3.42
11        deposit  completed   3319           113             3.40
12       transfer     failed   3477           118             3.39
13         retiro    pending    301            10             3.32
14       deposito  completed    302            10             3.31
15        payment   reversed   3333           110             3.30
16            fee  completed   3314           109             3.29
17     withdrawal    pending   3374           111             3.29
18           pago   reversed    307            10             3.26
19     withdrawal   reversed   3452           110             3.19
20         refund     failed   3438           108             3.14
21         refund   reversed   3414           107             3.13
22  transferencia  completed    193             6             3.11
23        deposit   reversed   3308           100             3.02
24        payment     failed   3285            99             3.01
25        deposit    pending   3353           100             2.98
26            fee    pending   3385            99             2.92
27            fee     failed   3389            99             2.92
28        deposit     failed   3410            99             2.90
29       transfer  completed   3492            97             2.78
30        payment  completed   3314            92             2.78
31         refund  completed   3579            98             2.74
32        payment    pending   3321            91             2.74
33     withdrawal     failed   3352            91             2.71
34     withdrawal  completed   3306            89             2.69
35         refund    pending   3492            92             2.63
36       transfer   reversed   3503            90             2.57
37           pago    pending    287             7             2.44
38       comision   reversed    295             7             2.37
39            fee   reversed   3388            80             2.36
40         retiro  completed    299             7             2.34
41           pago     failed    300             7             2.33
42  transferencia     failed    182             4             2.20
43         retiro   reversed    288             6             2.08
44       comision    pending    301             6             1.99
45       deposito     failed    306             6             1.96
46      reembolso   reversed    174             3             1.72
47       deposito   reversed    286             4             1.40

In [357]:
print(query("select amount from silver.stg_transactions where amount is not null limit 20"))

          amount
0   3.316971e+04
1   1.504819e+04
2   3.319303e+04
3   1.919954e+04
4   4.457140e+04
5   1.373060e+04
6   2.100776e+04
7   1.364749e+04
8   6.785840e+03
9   1.749867e+04
10  8.189130e+03
11  2.141947e+04
12  4.598096e+04
13  1.691729e+08
14  1.074271e+06
15  8.151796e+05
16  8.145882e+05
17  1.181131e+06
18  1.900331e+05
19  1.531954e+06

In [358]:
print(query("select min(amount) as min_amount, max(amount) as max_amount from silver.stg_transactions where amount is not null"))

   min_amount    max_amount
0        1.89  1.999953e+08

## Currency

In [359]:
print(query("select distinct currency from silver.stg_transactions limit 20"))

  currency
0      COP
1      ARS
2      UYU
3      MXN
4      PEN
5      BRL
6      CLP
7      EUR
8      USD

In [360]:
print(query("select count(*) from silver.stg_accounts where currency!= trim(currency)"))

   count
0      0

Based on this Currency is already normalized, so no transformation is required here, however, enforcing the same format is suitable in this case.

## Type

In [362]:
print(query("select count(*) from silver.stg_transactions where type is null"))

   count
0      0

In [361]:
print(query("select distinct lower(trim(type)) from silver.stg_transactions limit 20"))

            lower
0          retiro
1          refund
2   transferencia
3       reembolso
4             fee
5            pago
6        transfer
7         payment
8      withdrawal
9         deposit
10       deposito
11       comision

In this case, proper translation is required, as shown in the table below. Additionally, lowercase and trimming are required to ensure data consistency.

| original value | corrected value |
|----------------|----------------|
| retiro         | withdrawal      |
| transferencia  | transfer        |
| reembolso      | refund          |
| pago           | payment         |
| deposito       | deposit         |
| comision       | fee             |

## Category

In [364]:
print(query("select  lower(trim(category)) as category, count(*) from silver.stg_transactions group by lower(trim(category))"))

         category  count
0            None    825
1       utilities   5658
2          salary   5493
3            rent   5530
4       education   5568
5       insurance   5537
6       groceries   5517
7        shopping   5613
8    subscription   5501
9            null    863
10      transport   5493
11         dining   5664
12     healthcare   5667
13                   846
14         travel   5567
15            n/a    862
16     investment   5493
17  entertainment   5473
18          other   5616
19             na    900

In this case, proper null handling is necessary, as well as lowercasing certain values and trimming them.

## Merchant

In [365]:
print(query("select distinct merchant from silver.stg_transactions limit 20"))

      merchant
0         None
1       Amazon
2    Carrefour
3        IFood
4   HomeCenter
5
6      Elektra
7    McDonalds
8          N/A
9         Didi
10   Starbucks
11        Oxxo
12      Coppel
13     Netflix
14          NA
15     Walmart
16       Claro
17        Uber
18   PedidosYa
19   Falabella

In this case, we will solely remove the null values and address improper null handling, such as values like "NA" or "N/A".

## Channel

In [368]:
print(query("select count(*) from silver.stg_transactions where channel is null"))

   count
0      0

In [366]:
print(query("select distinct channel from silver.stg_transactions"))

  channel
0     pos
1  mobile
2     atm
3     web
4  branch

Everything is already normalized. Only verify:
- All values are lowercase
- No leading or trailing whitespaces

## Status

In [370]:
print(query("select count(*) from silver.stg_transactions where status is null"))

   count
0      0

In [371]:
print(query("select distinct lower(trim(status)) as status from silver.stg_transactions"))

      status
0  completed
1     failed
2    pending
3   reversed

In [372]:
print(query("select distinct status from silver.stg_transactions limit 20"))

      status
0     FAILED
1   REVERSED
2     failed
3    PENDING
4   reversed
5  COMPLETED
6  completed
7    pending

In this case, we only need to normalize the text by converting everything to lowercase and removing leading and trailing spaces. No null handling is required here.

## Description

In [376]:
print(query("select count(*) from silver.stg_transactions where length(description) != length(trim(regexp_replace(description, '\s+', '', 'g')))"))

   count
0  78740

It is demonstrated that we need to clean extra whitespacing in this field.

# Loans EDA

In [378]:
loans_df = pd.read_sql_table('stg_loans', con=engine , schema='silver')
loans_df.head()

,customer_id,loan_id,type,status,currency,end_date,principal,start_date,term_months,days_past_due,interest_rate,collateral_type,monthly_payment,outstanding_balance
0,CUST-0000002,LN-1428244D92,education,default,USD,2024-07-16,4.674530e+05,2023-07-22,12.0,243.0,19.25,none,43134.66,391480.59
1,CUST-0000002,LN-7299B81A8C,mortgage,current,BRL,2033-10-03,1.440199e+06,2023-11-25,120.0,0.0,10.47,none,19409.14,458237.28
2,CUST-0000004,LN-FC2C60F68B,MORTGAGE,current,USD,2029-12-13,3.485204e+05,2026-01-03,48.0,0.0,34.96,real_estate,13573.86,47304.13
3,CUST-0000004,LN-A09D3A4DAD,auto,default,USD,2026-11-05,4.264242e+05,2023-11-21,36.0,351.0,25.78,vehicle,17130.96,95622.06
4,CUST-0000004,LN-A7A9E05918,personal,paid_off,COP,2038-03-17,6.323956e+08,2023-06-04,180.0,0.0,34.99,none,18544659.01,0.00

In [379]:
loans_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7663 entries, 0 to 7662
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          7663 non-null   object
 1   loan_id              7663 non-null   object
 2   type                 7663 non-null   object
 3   status               7663 non-null   object
 4   currency             7663 non-null   object
 5   end_date             7663 non-null   object
 6   principal            7448 non-null   float64
 7   start_date           7663 non-null   object
 8   term_months          7663 non-null   float64
 9   days_past_due        7663 non-null   float64
 10  interest_rate        7663 non-null   float64
 11  collateral_type      7503 non-null   object
 12  monthly_payment      7439 non-null   float64
 13  outstanding_balance  7444 non-null   float64
dtypes: float64(6), object(8)
memory usage: 838.3+ KB

In [380]:
loans_df.isnull().sum()

customer_id              0
loan_id                  0
type                     0
status                   0
currency                 0
end_date                 0
principal              215
start_date               0
term_months              0
days_past_due            0
interest_rate            0
collateral_type        160
monthly_payment        224
outstanding_balance    219
dtype: int64

# Load ID

In [381]:
print(query("select count(distinct loan_id) from silver.stg_loans"))

   count
0   7663

In [382]:
print(query("select count(*) from silver.stg_loans"))

   count
0   7663

## Type

In [383]:
print(query("select distinct type from silver.stg_loans"))

        type
0  EDUCATION
1   BUSINESS
2   personal
3   MORTGAGE
4   mortgage
5   PERSONAL
6       AUTO
7       auto
8  education
9   business

In [384]:
print(query("select distinct lower(trim(type)) from silver.stg_loans"))

       lower
0   personal
1   mortgage
2       auto
3  education
4   business

In this case, no extra cleaning is required. Simply converting to lowercase and removing leading and trailing whitespaces is sufficient.

## Currency

In [386]:
print(query("select count(*) from silver.stg_loans where currency is null"))

   count
0      0

In [385]:
print(query("select distinct currency from silver.stg_loans"))

  currency
0      COP
1      ARS
2      UYU
3      MXN
4      PEN
5      BRL
6      CLP
7      USD

## Principal

In [387]:
print(query("select count(*) from silver.stg_loans where principal is null"))

   count
0    215

In [388]:
print(query("select * from silver.stg_loans where principal is null limit 10"))

    customer_id        loan_id      type      status currency    end_date  \
0  CUST-0000008  LN-D92E1842BB  business  delinquent      USD  10/03/2026
1  CUST-0000022  LN-57F0172E89  PERSONAL     CURRENT      BRL  2034-10-21
2  CUST-0000024  LN-344A4044FA  mortgage     current      USD  2029-11-24
3  CUST-0000027  LN-EBD76AB717  mortgage  delinquent      COP  2032-08-18
4  CUST-0000045  LN-D1E9E7CA41  PERSONAL  delinquent      USD  2026-10-26
5  CUST-0000081  LN-740A8BC8BB  mortgage     default      USD  2027-11-04
6  CUST-0000157  LN-095B3DD20A  MORTGAGE     current      USD  2031-10-05
7  CUST-0000200  LN-BA7B7CAC56      auto    paid_off      COP    20340623
8  CUST-0000208  LN-5A43E95A06  mortgage  delinquent      USD  2030-04-22
9  CUST-0000331  LN-DD54EAF446  business  delinquent      USD  2026-11-21

  principal  start_date  term_months  days_past_due  interest_rate  \
0      None  03-15-2025         12.0           78.0           4.21
1      None  2024-12-12        120.0            0.0          10.85
2      None  2025-12-15         48.0            0.0          26.84
3      None  2025-09-24         84.0           78.0          22.63
4      None  2024-11-05         24.0           44.0          11.97
5      None  19/11/2024         36.0          286.0          26.32
6      None  2024-11-10         84.0            0.0          31.38
7      None  2024-08-14        120.0            0.0          24.06
8      None  2025-05-18         60.0           66.0          24.43
9      None  2021-12-17         60.0           64.0          24.63

        collateral_type  monthly_payment  outstanding_balance
0           real_estate          7834.15         2.010867e+04
1               vehicle              NaN         1.472665e+05
2           real_estate         15000.44         3.922561e+05
3           real_estate      45175020.75         1.023830e+09
4                  none          5095.02         3.091594e+04
5           real_estate          5626.22         1.120849e+05
6           real_estate         14532.88         2.396421e+05
7                            38052999.00         0.000000e+00
8           real_estate          6777.06         2.304530e+05
9  investment_portfolio          1527.77         3.860608e+04

In [389]:
print(query("select * from silver.stg_loans where principal is not null limit 10"))

    customer_id        loan_id       type    status currency    end_date  \
0  CUST-0000002  LN-1428244D92  education   default      USD  2024-07-16
1  CUST-0000002  LN-7299B81A8C   mortgage   current      BRL  2033-10-03
2  CUST-0000004  LN-FC2C60F68B   MORTGAGE   current      USD  2029-12-13
3  CUST-0000004  LN-A09D3A4DAD       auto   default      USD  2026-11-05
4  CUST-0000004  LN-A7A9E05918   personal  paid_off      COP  2038-03-17
5  CUST-0000005  LN-E99131CE63   personal   default      USD  2042-04-23
6  CUST-0000005  LN-3C3E519A07   business   current      ARS  2028-10-16
7  CUST-0000005  LN-F66A8F5C85   business   default      ARS  2028-11-25
8  CUST-0000006  LN-23E05FF367  education   default      USD  2033-02-12
9  CUST-0000008  LN-67142D783E       auto   current      MXN  2031-11-13

      principal  start_date  term_months  days_past_due  interest_rate  \
0  4.674530e+05  2023-07-22         12.0          243.0          19.25
1  1.440199e+06  2023-11-25        120.0            0.0          10.47
2  3.485204e+05  2026-01-03         48.0            0.0          34.96
3  4.264242e+05  2023-11-21         36.0          351.0          25.78
4  6.323956e+08  2023-06-04        180.0            0.0          34.99
5  4.710853e+05  06/08/2022        240.0          304.0          24.48
6  1.972674e+08  2021-11-22         84.0            0.0          11.16
7  2.423001e+08  2022-01-01         84.0           98.0          30.82
8  9.293045e+04  2026-03-21         84.0          342.0          15.74
9  3.418694e+06  2022-01-04        120.0            0.0          33.14

   collateral_type  monthly_payment  outstanding_balance
0             none         43134.66         3.914806e+05
1             none         19409.14         4.582373e+05
2      real_estate         13573.86         4.730413e+04
3          vehicle         17130.96         9.562206e+04
4             none      18544659.01         0.000000e+00
5             none          9686.22         1.923249e+05
6  savings_account       3394317.30         1.819252e+08
7  savings_account       7062191.90         5.132105e+07
8             none          1832.06         8.993466e+04
9          vehicle         98146.62         1.150599e+06

CUST-0000002 | LN-7299B81A8C | mortgage  | current  | BRL      | 2033-10-03 |   1440199.16 | 2023-11-25 |         120 |             0 |         10.47 | none            |        19409.14 |           458237.28

In [394]:
print(query("select count(*) from silver.stg_loans where principal is null and monthly_payment is null"))

   count
0      7

In [407]:
print(query("""
with monthly_interest_rate as (
    select 
    loan_id,
    monthly_payment,
    interest_rate,
    term_months,
    (interest_rate/12)*1/100 as monthly_interest_rate
    from silver.stg_loans
    where interest_rate is not null)
select loan_id, monthly_interest_rate, interest_rate, term_months,monthly_payment*
((((1+monthly_interest_rate)^term_months)-1)/((1+monthly_interest_rate)^term_months*monthly_interest_rate)) as calculated_principal
from monthly_interest_rate where loan_id = 'LN-A7A9E05918'
"""))

         loan_id  monthly_interest_rate  interest_rate  term_months  \
0  LN-A7A9E05918               0.029158          34.99        180.0

   calculated_principal
0          6.323956e+08

In [409]:
print(query("""
select count(*) from silver.stg_loans where principal is null and monthly_payment is null
"""))

   count
0      7

## Outsanding Balances

In [439]:
print(query("select outstanding_balance, principal, days_past_due from silver.stg_loans where outstanding_balance>principal"))

Empty DataFrame
Columns: [outstanding_balance, principal, days_past_due]
Index: []

In [411]:
print(query("select * from silver.stg_loans where outstanding_balance is null limit 10"))

    customer_id        loan_id      type      status currency    end_date  \
0  CUST-0000039  LN-E2CD4979AE  personal     CURRENT      UYU  2025-08-13
1  CUST-0000177  LN-7619EC56EC  mortgage  delinquent      USD  2025-10-20
2  CUST-0000240  LN-FA955B25F0  mortgage    paid_off      USD  2030-01-31
3  CUST-0000319  LN-018A5FE6F1  mortgage    paid_off      USD  2045-12-04
4  CUST-0000359  LN-D58EC04EC7      auto     default      USD  2025-10-05
5  CUST-0000361  LN-47206F8EBF  personal     default      ARS  2044-09-25
6  CUST-0000415  LN-14E0C8DEB0      auto    paid_off      USD  2026-05-14
7  CUST-0000417  LN-95CD7C761B  mortgage     default      BRL  2038-08-06
8  CUST-0000446  LN-6BC4901E59  mortgage  delinquent      USD  2027-11-22
9  CUST-0000468  LN-1162E4C06C  business     default      UYU  2029-09-11

     principal  start_date  term_months  days_past_due  interest_rate  \
0   4828199.65  2023-08-24         24.0            0.0          14.98
1    372108.30  2022-11-05         36.0            7.0           7.47
2    391020.70  2023-03-09         84.0            0.0          31.32
3    317502.24  2026-03-19        240.0            0.0          24.71
4    195114.53  2024-10-10         12.0          328.0          10.76
5  98495307.79    20250108        240.0          113.0          27.34
6    493961.51  2021-06-09         60.0            0.0           9.18
7    533345.94  2023-10-24        180.0          334.0          19.35
8    265951.54    20231213         48.0           19.0          28.54
9   2775633.22  2024-10-07         60.0          278.0          26.87

   collateral_type  monthly_payment outstanding_balance
0             none        234057.34                None
1      real_estate         11569.76                None
2      real_estate         11529.62                None
3             null          6587.36                None
4          vehicle         17222.71                None
5          vehicle       2254165.16                None
6          vehicle         10297.03                None
7      real_estate          9112.04                None
8      real_estate              NaN                None
9  savings_account         84539.34                None

In [440]:
print(query("""
select min(outstanding_balance), max(outstanding_balance) from silver.stg_loans where outstanding_balance is not null
"""))

   min           max
0  0.0  1.843015e+09

In [459]:
import numpy as np
import pandas as pd

# 1. Filter out rows with nulls in critical math columns (equivalent to your WHERE clause)
df = pd.read_sql_table('stg_loans', con=engine , schema='silver')
valid_loans = df[
    df["interest_rate"].notna()
    & df["monthly_payment"].notna()
    & df["outstanding_balance"].notna()
].copy()

# 2. Calculate the monthly interest rate
valid_loans["monthly_interest_rate"] = (valid_loans["interest_rate"] / 12) * (
    1 / 100
)

# 3. Calculate the temporal value using the correct mathematical isolation formula
# (This handles the 1 - (Balance * Rate / Payment) component)
valid_loans["temporal_value"] = 1 - (
    (valid_loans["outstanding_balance"] / valid_loans["monthly_payment"])
    * valid_loans["monthly_interest_rate"]
)

# 4. Use vector change to solve for n (the negative log change)
# We use np.where to safely avoid errors with logs of 0 or negative values
valid_loans["calculated_term_months"] = np.where(
    valid_loans["temporal_value"] > 0,
    -(
        np.log(valid_loans["temporal_value"])
        / np.log(1 + valid_loans["monthly_interest_rate"])
    ),
    np.nan,  # Returns NaN if data is corrupt or loan is already paid off
)

# 5. Keep only the columns you want to inspect
result_df = valid_loans[
    [
        "loan_id",
        "monthly_interest_rate",
        "term_months",
        "end_date",
        "start_date",
        "calculated_term_months",
        "days_past_due",
        "principal",
        "outstanding_balance",
        "monthly_payment",
        "status"
    ]
]

result_df

,loan_id,monthly_interest_rate,term_months,end_date,start_date,calculated_term_months,days_past_due,principal,outstanding_balance,monthly_payment,status
0,LN-1428244D92,0.016042,12.0,2024-07-16,2023-07-22,9.886971,243.0,4.674530e+05,3.914806e+05,43134.66,default
1,LN-7299B81A8C,0.008725,120.0,2033-10-03,2023-11-25,26.551985,0.0,1.440199e+06,4.582373e+05,19409.14,current
2,LN-FC2C60F68B,0.029133,48.0,2029-12-13,2026-01-03,3.728093,0.0,3.485204e+05,4.730413e+04,13573.86,current
3,LN-A09D3A4DAD,0.021483,36.0,2026-11-05,2023-11-21,6.009564,351.0,4.264242e+05,9.562206e+04,17130.96,default
4,LN-A7A9E05918,0.029158,180.0,2038-03-17,2023-06-04,-0.000000,0.0,6.323956e+08,0.000000e+00,18544659.01,paid_off
...,...,...,...,...,...,...,...,...,...,...,...
7657,LN-4BF562C3D4,0.005933,84.0,2032-06-05,2025-07-12,59.145359,0.0,1.817839e+06,1.370499e+06,27542.82,current
7659,LN-8A9645A8C8,0.023358,12.0,2026-04-25,2025-04-30,9.567880,174.0,4.468936e+05,3.660390e+05,43134.47,default
7660,LN-45342FABAA,0.027675,120.0,2036-02-05,03-29-2026,69.769529,0.0,1.644537e+06,1.454666e+06,47299.71,CURRENT
7661,LN-9462AE47C4,0.005633,36.0,2025-01-22,2022-02-07,28.566679,0.0,4.455789e+05,3.608073e+05,13709.34,current
7662,LN-FE6ED9ED79,0.020092,180.0,2038-06-26,2023-09-13,48.466754,19.0,1.882679e+08,1.198160e+08,3891010.79,delinquent

In [463]:
print(query("select count(*), lower(trim(status)) from silver.stg_loans where outstanding_balance is null group by lower(trim(status))"))

   count       lower
0     53  delinquent
1     55     current
2     51    paid_off
3     60     default

As can be seen here, there is no clear or deterministic way to obtain the outstanding balance for null values. This is in contrast with fields such as `principal` or `monthly_payments`, which are deterministic.

Additionally, we observe that some users have already paid off their debt, even though it was forecasted to be paid within 15 years.

## Interest Rate

In [442]:
print(query("select count(*) from silver.stg_loans where interest_rate is null"))

   count
0      0

In [441]:
print(query("""
select min(interest_rate), max(interest_rate) from silver.stg_loans where interest_rate is not null
"""
))

    min   max
0  3.01  35.0

Interest_rate has no null values nor negative values, which fits with standard values for interest rate.

## Term Months

In [443]:
print(query("select count(*) from silver.stg_loans where term_months is null"))

   count
0      0

In [444]:
print(query("select min(term_months), max(term_months) from silver.stg_loans where term_months is not null"))

    min    max
0  12.0  360.0

## Monthly Payments

In [445]:
print(query("select count(*) from silver.stg_loans where monthly_payment is null"))

   count
0    224

In [446]:
print(query("select count(*) from silver.stg_loans where monthly_payment is null and principal is null"))

   count
0      7

## Start_date

In [447]:
print(query("select length(start_date) as start_date_length, count(*) from silver.stg_loans group by length(start_date)"))

   start_date_length  count
0                 10   7173
1                  8    490

In [449]:
format_1_count=query("select count(*) from silver.stg_loans where start_date like '____-__-__'")
format_2_count=query("select count(*) from silver.stg_loans where start_date like '__-__-____'")
format_3_count=query("select count(*) from silver.stg_loans where start_date like '__/__/____'")
format_4_count=query("select count(*) from silver.stg_loans where start_date like '________'")
total_count=query("select count(*) from silver.stg_loans")
if (format_1_count['count'][0] + format_2_count['count'][0] + format_3_count['count'][0] \
    + format_4_count['count'][0]) == total_count['count'][0]:
    print("All date values fit into one of the four formats")

All date values fit into one of the four formats

In [450]:
print(query("select start_date from silver.stg_loans where start_date like '________' limit 10"))
print(query("select start_date from silver.stg_loans where start_date like '__-__-____' limit 10"))
print(query("select start_date from silver.stg_loans where start_date like '____-__-__' limit 10"))
print(query("select start_date from silver.stg_loans where start_date like '____-__-__' limit 10"))

  start_date
0   20230630
1   20210619
2   20231104
3   20240922
4   20250104
5   20250118
6   20240221
7   20230601
8   20220914
9   20241023
   start_date
0  03-15-2025
1  10-18-2024
2  10-04-2025
3  10-09-2023
4  04-27-2025
5  05-29-2021
6  12-20-2025
7  09-06-2023
8  12-18-2025
9  10-11-2022
   start_date
0  2023-07-22
1  2023-11-25
2  2026-01-03
3  2023-11-21
4  2023-06-04
5  2021-11-22
6  2022-01-01
7  2026-03-21
8  2022-01-04
9  2024-01-28
   start_date
0  2023-07-22
1  2023-11-25
2  2026-01-03
3  2023-11-21
4  2023-06-04
5  2021-11-22
6  2022-01-01
7  2026-03-21
8  2022-01-04
9  2024-01-28

In this case it has been demostrated that we have four different formats for the dates:
- YYYY-MM-DD
- DD/MM/YYYY
- MM-DD-YYYY
- YYYYMMDD

Additionally, we have to null dates.

## End Date

In [451]:
print(query("select length(start_date) as start_date_length, count(*) from silver.stg_loans group by length(start_date)"))

   start_date_length  count
0                 10   7173
1                  8    490

In [452]:
format_1_count=query("select count(*) from silver.stg_loans where end_date like '____-__-__'")
format_2_count=query("select count(*) from silver.stg_loans where end_date like '__-__-____'")
format_3_count=query("select count(*) from silver.stg_loans where end_date like '__/__/____'")
format_4_count=query("select count(*) from silver.stg_loans where end_date like '________'")
total_count=query("select count(*) from silver.stg_loans")
if (format_1_count['count'][0] + format_2_count['count'][0] + format_3_count['count'][0] \
    + format_4_count['count'][0]) == total_count['count'][0]:
    print("All date values fit into one of the four formats")

All date values fit into one of the four formats

In [453]:
print(query("select end_date from silver.stg_loans where end_date like '________' limit 10"))
print(query("select end_date from silver.stg_loans where end_date like '__-__-____' limit 10"))
print(query("select end_date from silver.stg_loans where end_date like '____-__-__' limit 10"))
print(query("select end_date from silver.stg_loans where end_date like '____-__-__' limit 10"))

   end_date
0  20390315
1  20250323
2  20330409
3  20400811
4  20281010
5  20270816
6  20241125
7  20250914
8  20380930
9  20231121
     end_date
0  02-15-2027
1  08-16-2042
2  08-21-2051
3  07-02-2044
4  04-09-2029
5  07-17-2029
6  02-04-2028
7  02-02-2034
8  12-14-2027
9  05-16-2026
     end_date
0  2024-07-16
1  2033-10-03
2  2029-12-13
3  2026-11-05
4  2038-03-17
5  2042-04-23
6  2028-10-16
7  2028-11-25
8  2033-02-12
9  2031-11-13
     end_date
0  2024-07-16
1  2033-10-03
2  2029-12-13
3  2026-11-05
4  2038-03-17
5  2042-04-23
6  2028-10-16
7  2028-11-25
8  2033-02-12
9  2031-11-13

In this case it has been demostrated that we have four different formats for the dates:
- YYYY-MM-DD
- DD/MM/YYYY
- MM-DD-YYYY
- YYYYMMDD

Additionally, we have to null dates.

## Status

In [455]:
print(query("select distinct lower(trim(status)) from silver.stg_loans"))

        lower
0  delinquent
1     current
2    paid_off
3     default

In this case, there are no null values. We only need to remove leading and trailing spaces from the `status` field, as well as convert everything to lowercase.

## Days Past Due

In [457]:
print(query("select count(*) from silver.stg_loans where days_past_due is null"))

   count
0      0

In [456]:
print(query("select min(days_past_due), max(days_past_due) from silver.stg_loans"))

   min    max
0  0.0  365.0

In this case no normalization is required, however we need to enforce a int constraint.

## Collateral Type

In [458]:
print(query("select distinct collateral_type from silver.stg_loans"))

        collateral_type
0                  None
1                    NA
2                  none
3
4                  null
5  investment_portfolio
6               vehicle
7       savings_account
8           real_estate
9                   N/A

In this case, there are multiple null values that are represented using different placeholders rather than a consistent null marker. Therefore, proper normalization is required.

## Digital Engagement

In [464]:
print(query("""
select 
    digital_engagement::jsonb->>'mobile_app_registered' as mobile_app_registered
    from silver.stg_customers
"""))

     mobile_app_registered
0                    false
1                     true
2                     true
3                    false
4                     true
...                    ...
4995                  true
4996                 false
4997                 false
4998                 false
4999                  true

[5000 rows x 1 columns]

In [465]:
print(query("""
select 
    distinct digital_engagement::jsonb->>'mobile_app_registered' as mobile_app_registered
    from silver.stg_customers
"""))

  mobile_app_registered
0                  true
1                 false

## Web Banking Registered

In [466]:
print(query("""
select 
    distinct digital_engagement::jsonb->>'web_banking_registered' as web_banking_registered
    from silver.stg_customers
"""
))

  web_banking_registered
0                   true
1                  false

## last_login_date

In [468]:
print(query("""
with base as (
    select digital_engagement::jsonb->>'last_login_date' as last_login_date
    from silver.stg_customers
    )
select count(*) from base where last_login_date is null or length(last_login_date) = 0
"""
))

   count
0      0

In [467]:
print(query("""
with base as (
    select digital_engagement::jsonb->>'last_login_date' as last_login_date
    from silver.stg_customers
    )
select length(last_login_date) as last_login_date_length, count(*) from base group by length(last_login_date) order by last_login_date_length;

"""
))

   last_login_date_length  count
0                       8    271
1                      10   4729

## Average Monthly Logins

In [469]:
print(query("""
with base as (
    select digital_engagement::jsonb->>'avg_monthly_logins' as avg_monthly_logins
    from silver.stg_customers
    )
select length(avg_monthly_logins) as avg_monthly_logins_length, count(*) from base group by length(avg_monthly_logins) order by avg_monthly_logins_length;

"""))

   avg_monthly_logins_length  count
0                        0.0     78
1                        1.0    741
2                        2.0   3970
3                        3.0     67
4                        4.0     76
5                        NaN     68

In [485]:
print(query("""
with base as (
    select digital_engagement::jsonb->>'avg_monthly_logins' as avg_monthly_logins
    from silver.stg_customers
    )
select count(*) from base where avg_monthly_logins is null or length(avg_monthly_logins) = 0

"""))

   count
0    146

In [487]:
print(query("""
with base as (
    select digital_engagement::jsonb->>'avg_monthly_logins' as avg_monthly_logins
    from silver.stg_customers
    )
select distinct avg_monthly_logins, count(*) from base where trim(avg_monthly_logins) ~ '[^0-9]' group by avg_monthly_logins

"""))

  avg_monthly_logins  count
0                 NA     85
1               null     76
2                N/A     67

In [486]:
print(query("""
with base as (
    select digital_engagement::jsonb->>'avg_monthly_logins' as avg_monthly_logins
    from silver.stg_customers
    )
select distinct avg_monthly_logins from base where trim(avg_monthly_logins) not like '[^0-9]'

"""))

   avg_monthly_logins
0                  26
1                  52
2                  56
3                  22
4                  58
..                ...
60                 24
61                 41
62                 12
63                 39
64                 48

[65 rows x 1 columns]

## Preferred Channel

In [470]:
print(query("""
with base as (
    select digital_engagement::jsonb->>'preferred_channel' as preferred_channel
    from silver.stg_customers
    )
select distinct preferred_channel from base
"""))

  preferred_channel
0            mobile
1               atm
2             phone
3            branch
4               web

## Push Notifications

In [471]:
print(query("""
with base as (
    select digital_engagement::jsonb->>'push_notifications' as push_notifications
    from silver.stg_customers
    )

select distinct push_notifications from base
"""))

  push_notifications
0                 no
1                  0
2                  1
3                yes
4               true
5              false

## Paperless Statements

In [472]:
print(query("""
with base as (
    select digital_engagement::jsonb->>'paperless_statements' as paperless_statements
    from silver.stg_customers
    )

select distinct paperless_statements from base
"""))

  paperless_statements
0                   no
1                    0
2                   si
3                    1
4                 true
5                false

# Credit Info

## Credit Score

In [488]:
print(query("""
with base as (
    select credit_info::jsonb->>'credit_score' as credit_score
    from silver.stg_customers
    )
    select count(*) from base where credit_score is null or length(credit_score) = 0
"""))

   count
0      0

In [497]:
print(query("""
with base as (
    select credit_info::jsonb->>'credit_score' as credit_score
    from silver.stg_customers
    )
    select distinct credit_score from base where trim(credit_score) !~ '^-?[0-9]+$'
"""))

Empty DataFrame
Columns: [credit_score]
Index: []

In [501]:
print(query("""
with base as (
    select credit_info::jsonb->>'credit_score' as credit_score
    from silver.stg_customers
    )
    select count(*) from base where trim(credit_score) ~ '^-[0-9]+$'
"""))

   count
0     45

## Currency

In [502]:
print(query("""
with base as (
    select credit_info::jsonb->>'currency' as currency
    from silver.stg_customers
    )
    select distinct currency from base
"""))

  currency
0      CLP
1      BRL
2      PEN
3      MXN
4      ARS
5      UYU
6      COP

In [503]:
print(query("""
with base as (
    select credit_info::jsonb->>'currency' as currency
    from silver.stg_customers
    )
    select count(*)  from base where currency is null or length(currency) = 0
"""))

   count
0      0

## Utilization Percentage

In [504]:
print(query("""
with base as (
    select credit_info::jsonb->>'utilization_pct' as utilization_pct
    from silver.stg_customers
    )
    select count(*) from base where utilization_pct is null or length(utilization_pct) = 0
"""))

   count
0      0

In [505]:
print(query("""
with base as (
    select credit_info::jsonb->>'utilization_pct' as utilization_pct
    from silver.stg_customers
    )
    select count(*) from base where utilization_pct !~ '^-?[0-9]+(\.[0-9]+)?$'
"""))

   count
0     19

In [508]:
print(query("""
with base as (
    select credit_info::jsonb->>'utilization_pct' as utilization_pct
    from silver.stg_customers
    )
    select utilization_pct from base where utilization_pct !~ '^-?[0-9]+(\.[0-9]+)?$'
"""))

   utilization_pct
0         89.5 USD
1           $19.28
2            74,19
3         9.72 USD
4            19,91
5             83,5
6        18.67 USD
7        42.95 USD
8           $78.26
9            61,08
10       20.69 USD
11       45.28 USD
12           $39.5
13          $89.55
14       49.29 USD
15           42,38
16          $56.46
17           84,23
18           $0.67

## Total_limit

In [509]:
print(query("""
with base as (
    select credit_info::jsonb->>'total_limit' as total_limit
    from silver.stg_customers
    )
    select count(*) from base where total_limit is null or length(total_limit) = 0
"""))

   count
0      0

In [511]:
print(query("""
with base as (
    select credit_info::jsonb->>'total_limit' as total_limit
    from silver.stg_customers
    )
    select count(*) from base where total_limit !~ '^-?[0-9]+(\.[0-9]+)?$'
"""))

   count
0    122

In [512]:
print(query("""
with base as (
    select credit_info::jsonb->>'total_limit' as total_limit
    from silver.stg_customers
    )
    select total_limit from base where total_limit !~ '^-?[0-9]+(\.[0-9]+)?$' limit 20;
"""))

         total_limit
0       $89026960.45
1          937376,78
2           90537,02
3       $12207284.19
4          558764,15
5           73016,94
6          121655,02
7      $199745458.68
8   508611231.14 USD
9          139055,23
10  194355666.99 USD
11       343776774,8
12        $2685394.1
13         860577,94
14    3860006.56 USD
15       74979229,96
16   167857969.5 USD
17  142528557.29 USD
18     $665762079.12
19     $181873892.79

## Total Used

In [513]:
print(query("""
with base as (
    select credit_info::jsonb->>'total_used' as total_used
    from silver.stg_customers
    )
    select count(*) from base where total_used is null or length(total_used) = 0
"""))

   count
0      0

In [514]:
print(query("""
with base as (
    select credit_info::jsonb->>'total_limit' as total_limit
    from silver.stg_customers
    )
    select count(*) from base where total_limit !~ '^-?[0-9]+(\.[0-9]+)?$'
"""))

   count
0    122

In [515]:
print(query("""
with base as (
    select credit_info::jsonb->>'total_limit' as total_limit
    from silver.stg_customers
    )
    select total_limit from base where total_limit !~ '^-?[0-9]+(\.[0-9]+)?$' limit 20;
"""))

         total_limit
0       $89026960.45
1          937376,78
2           90537,02
3       $12207284.19
4          558764,15
5           73016,94
6          121655,02
7      $199745458.68
8   508611231.14 USD
9          139055,23
10  194355666.99 USD
11       343776774,8
12        $2685394.1
13         860577,94
14    3860006.56 USD
15       74979229,96
16   167857969.5 USD
17  142528557.29 USD
18     $665762079.12
19     $181873892.79

## Num Credit Accounts

In [523]:
print(query("""
with base as (
    select credit_info::jsonb->>'num_credit_accounts' as num_credit_accounts
    from silver.stg_customers
    )
    select count(*) from base where num_credit_accounts is null or length(num_credit_accounts) = 0;
"""))

   count
0      0

In [522]:
print(query("""
with base as (
    select credit_info::jsonb->>'num_credit_accounts' as num_credit_accounts
    from silver.stg_customers
    )
    select count(*) from base where num_credit_accounts ~ '^-?[0-9]+$';
"""))

   count
0   5000

In [521]:
print(query("""
with base as (
    select credit_info::jsonb->>'num_credit_accounts' as num_credit_accounts
    from silver.stg_customers
    )
    select count(*) from base where num_credit_accounts !~ '^-?[0-9]+$';
"""))

   count
0      0

In [525]:
print(query("""
with base as (
    select credit_info::jsonb->>'num_credit_accounts' as num_credit_accounts
    from silver.stg_customers
    )
    select distinct * from base limit 20;
"""))

  num_credit_accounts
0                   7
1                   2
2                   8
3                   9
4                   3
5                   6
6                   5
7                   1
8                  10
9                   4

## Oldest Account Age Months

In [526]:
print(query("""
with base as (
    select credit_info::jsonb->>'oldest_account_age_months' as oldest_account_age_months
    from silver.stg_customers
    )
    select distinct * from base limit 20;
"""))

   oldest_account_age_months
0                        247
1                        124
2                        165
3                        160
4                        157
5                         26
6                        140
7                        195
8                        102
9                         92
10                       200
11                       164
12                       184
13                       332
14                       268
15                       146
16                        52
17                       170
18                        56
19                        22

In [529]:
print(query("""
with base as (
    select credit_info::jsonb->>'oldest_account_age_months' as oldest_account_age_months
    from silver.stg_customers
    )
    select count(*) from base where oldest_account_age_months !~ '^-?[0-9]+$';
"""))

   count
0      0

In [532]:
print(query("""
with base as (
    select credit_info::jsonb->>'oldest_account_age_months' as oldest_account_age_months
    from silver.stg_customers
    )
    select count(*) from base where oldest_account_age_months ~ '^-?[0-9]+$' and oldest_account_age_months is not null and length(oldest_account_age_months) > 0;
"""))

   count
0   5000

## Late Payments 12M

In [534]:
print(query("""
with base as (
    select credit_info::jsonb->>'late_payments_12m' as late_payments_12m
    from silver.stg_customers
    )
    select distinct * from base limit 20;
"""))

   late_payments_12m
0                  7
1                  2
2                  0
3                  8
4                  9
5                  3
6                  6
7                  5
8                 11
9                  1
10                10
11                 4
12                12

In [535]:
print(query("""
with base as (
    select credit_info::jsonb->>'late_payments_12m' as late_payments_12m
    from silver.stg_customers
    )
    select count(*) from base where late_payments_12m is not null and length(late_payments_12m) > 0;
"""))

   count
0   5000

## Inquiries

In [536]:
print(query("""
with base as (
    select credit_info::jsonb->>'inquiries_6m' as inquiries_6m
    from silver.stg_customers
    )
    select distinct * from base limit 20;
"""))

   inquiries_6m
0             7
1             2
2             0
3             8
4             9
5             3
6             6
7             5
8             1
9            10
10            4

In [538]:
print(query("""
with base as (
    select credit_info::jsonb->>'inquiries_6m' as inquiries_6m
    from silver.stg_customers
    )
    select count(*) from base where inquiries_6m is null or length(inquiries_6m) = 0;
"""))

   count
0      0

## Bankrupcy Flag

In [540]:
print(query("""
with base as (
    select credit_info::jsonb->>'bankruptcy_flag' as bankruptcy_flag
    from silver.stg_customers
    )

select distinct bankruptcy_flag from base
"""))

  bankruptcy_flag
0               0
1               N
2               1
3               Y
4            true
5           false